# Generated by Django 4.2.27 on 2026-04-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_searchhistory_interactionlog_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactionlog',
            old_name='book_id',
            new_name='product_id',
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='action_type',
            field=models.CharField(choices=[('VIEW_PRODUCT', 'Viewed Product'), ('ADD_TO_CART', 'Added to Cart'), ('REMOVE_FROM_CART', 'Removed from Cart')], max_length=20),
        ),
    ]
